home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('',views.HomePage.as_view(),name='index'),
    path('create-menu/',views.create_new_menu,name='create-menu'),
    path('list-menus/<int:id>/',views.list_menus,name='list-menus'),
    path('add-cart/<int:id>/',views.add_cart,name='add-cart'),
    path('remove-cart/<int:id>/',views.remove_cart,name='remove-cart'),
    path('cart/<int:id>/',views.cart_view,name='cart-view'),
    path('checkout/<int:id>/',views.check_out,name='check-out'),
]

online_food_src/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    path('',include('home.urls',namespace='home')),

]

home/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Restaurant(models.Model):
    owner = models.OneToOneField(User,on_delete=models.CASCADE,related_name='res')
    name = models.CharField(max_length=128,unique=True)
    description = models.TextField()
    area = models.CharField(max_length=128)
    city = models.CharField(max_length=128)
    image = models.URLField(max_length=500)
    ratings = models.PositiveSmallIntegerField(default=0)
    lat = models.DecimalField(max_digits=22, decimal_places=16, blank=True, null=True)
    lon = models.DecimalField(max_digits=22, decimal_places=16, blank=True, null=True)
    limit = models.IntegerField(default=0)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name[:20]

class Food(models.Model):
    restaurant = models.ForeignKey(Restaurant,on_delete=models.CASCADE,related_name='menu',null=True)
    food_name = models.CharField(max_length=56)
    price = models.PositiveIntegerField()
    ratings = models.PositiveSmallIntegerField(default=0)
    image = models.URLField(blank=True,null=True)

    def __str__(self):
        return self.food_name[:20]


class Cart(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    res = models.ForeignKey(Restaurant,on_delete=models.CASCADE)
    items = models.ManyToManyField(Food)
    price = models.IntegerField(default=0)

    def __str__(self):
        return f"User: {self.user}, Res:{self.res}"

profiles/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from allauth.account.signals import email_confirmed
from django.dispatch import receiver

class User(AbstractUser):
    pass

    def __str__(self):
        return self.email


class UserInfo(models.Model):
    """
    Stores the Information About Users
    """
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='info')
    is_restaurant = models.BooleanField(default=False)

    def __str__(self):
        return f"Info OF {self.user}"

home/forms.py
from django import forms
from django.db.models import fields

from .models import Restaurant,Food

class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = ['name', 'description', 'area', 'city','image','limit','lat','lon']

class FoodForm(forms.ModelForm):
    class Meta:
        model = Food
        fields = ['food_name','price','ratings','image',]

profiles/forms.py
from allauth.account.forms import SignupForm , LoginForm
from django import forms
from allauth.account.adapter import DefaultAccountAdapter 
from django.forms import ValidationError

from .models import UserInfo


class CustomLoginForm(LoginForm):
     def __init__(self, *args, **kwargs):
        super(CustomLoginForm, self).__init__(*args, **kwargs)
        self.fields['login'].widget.attrs = {'placeholder': 'Username or Email', 'autofocus': 'autofocus'}


class CustomSignupForm(SignupForm):
    """
    Custom SignUp Form and Also Created New user_info Object
    """

    first_name = forms.CharField(max_length=30, label='First Name') 
    last_name = forms.CharField(max_length=30, label='Last Name')
    signup_as_restaurant = forms.BooleanField(required=False)

    def save(self, request):

        # Ensure you call the parent class's save.
        # .save() returns a User object.
        user = super(CustomSignupForm, self).save(request)

        user.first_name = self.cleaned_data['first_name'] 
        user.last_name = self.cleaned_data['last_name']

        signup_as_restaurant = self.cleaned_data['signup_as_restaurant']

        user.save()

        # age = self.cleaned_data['age']
        # gender = self.cleaned_data['gender']
        # phone = str(self.cleaned_data['phone'])
        # department_year = self.cleaned_data['department_year']

        user_info , created = UserInfo.objects.get_or_create(
            user=user,
            is_restaurant = signup_as_restaurant
        )

        return user

home/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.views.generic import View
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotAllowed, JsonResponse
from django.core.exceptions import ValidationError,PermissionDenied
from django.contrib import messages

from .models import Restaurant,Food,Cart
from .forms import RestaurantForm,FoodForm

User = get_user_model()

class HomePage(View):
    def get(self,request,format=None):
        if(request.user.is_authenticated and request.user.info.is_restaurant):
            res = Restaurant.objects.filter(owner=request.user)
            if(len(res)==0):
                form = RestaurantForm()
                return render(request,'home/res_create.html',{'form':form})
            res = res.first()
            menus = res.menu.all()
            return render(request,'home/index_res.html',{'res':res,'menus':menus})

        restaurants = Restaurant.objects.all()
        return render(request,'home/index.html',{'restaurants':restaurants})

    def post(self,request,formt=None):
        if not (request.user.is_authenticated and request.user.info.is_restaurant):
            raise PermissionDenied()
        
        form = RestaurantForm(request.POST)
        if(form.is_valid()):
            instance = form.save(commit=False)
            instance.owner = request.user
            instance.save()

        return redirect('home:index')


def create_new_menu(request):
    if not (request.user.is_authenticated and request.user.info.is_restaurant):
        raise PermissionDenied() # Only Owner can Add Menu
    form = FoodForm()   
    if(request.method == 'POST'):
        form = FoodForm(request.POST)
        if(form.is_valid()):
            instance = form.save(commit=False)
            instance.restaurant = request.user.res
            instance.save()

        return redirect('home:index')

    return render(request,'home/menu_create.html',{'form':form})


@login_required
def list_menus(request,id):
    res = get_object_or_404(Restaurant,pk=id)
    menus = res.menu.all()
    return render(request,'home/menu_list.html',{'menus':menus,'res':res})


@login_required
def add_cart(request,id):
    menu = get_object_or_404(Food,pk=id)
    res = menu.restaurant
    cart,created = Cart.objects.get_or_create(res=res,user=request.user)
    cart.items.add(menu)
    cart.price += (menu.price)
    cart.save()
    return redirect('home:cart-view',id=cart.res.id)

@login_required
def remove_cart(request,id):
    menu = get_object_or_404(Food,pk=id)
    res = menu.restaurant
    cart,created = Cart.objects.get_or_create(res=res,user=request.user)
    cart.items.remove(menu)
    cart.price -= (menu.price)
    cart.save()
    return redirect('home:cart-view',id=cart.res.id)


@login_required
def cart_view(request,id):
    res = get_object_or_404(Restaurant,pk=id)
    cart,created = Cart.objects.get_or_create(res=res,user=request.user)
    menus = cart.items.all()
    return render(request,'home/cart.html',{'menus':menus,'cart':cart,'res_id':res.id})


@login_required
def check_out(request,id):
    cart = Cart.objects.get(id=id)
    price = cart.price
    limit = cart.res.limit
    if(price<limit):
        messages.info(request,"Add more items to cart!")
        return redirect('home:cart-view',id=cart.res.id)
    cart.delete()
    return render(request,'home/order_placed.html',{'price':price})

home/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="base.css">
    <link rel="stylesheet" type="text/css" href="index.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div id="common">
        <div class="header">
            <nav>
                <ul>
                    <li><a>Home</a></li> 
                    <li><a>Contact</a></li> 
                    <li><a>Services</a></li> 
                    <li><a>Sign up</a></li>
                </ul>
            </nav>
            <div class="catch">
                <div class="logo">
                    <img src="bee.png">
                </div>
                <h1>HungerHive</h1>
            </div>    
        </div>
        <div class="container">
            <h2><a>Categories</a></h2>
            <p>Let's start with your favourite kinds</p>
            <div class="row">
                <div class="slide">
                    <div class="heading">
                        <img src="https://www.jessicagavin.com/wp-content/uploads/2020/12/how-to-make-risotto-22-1200.jpg">
                    </div>
                    <div class="desc">
                        <p>Italians</p>
                    </div>
                </div>
                <div class="slide">
                    <div class="heading">
                        <img src="https://www.jessicagavin.com/wp-content/uploads/2020/12/how-to-make-risotto-22-1200.jpg">
                    </div>
                    <div class="desc">
                        <p>Italians</p>
                    </div>
                </div>
                <div class="slide">
                    <div class="heading">
                        <img src="https://www.jessicagavin.com/wp-content/uploads/2020/12/how-to-make-risotto-22-1200.jpg">
                    </div>
                    <div class="desc">
                        <p>Italians</p>
                    </div>
                </div>
                <div class="slide">
                    <div class="heading">
                        <img src="https://www.jessicagavin.com/wp-content/uploads/2020/12/how-to-make-risotto-22-1200.jpg">
                    </div>
                    <div class="desc">
                        <p>Italians</p>
                    </div>
                </div>
                <div class="slide">
                    <div class="heading">
                        <img src="https://www.jessicagavin.com/wp-content/uploads/2020/12/how-to-make-risotto-22-1200.jpg">
                    </div>
                    <div class="desc">
                        <p>Italians</p>
                    </div>
                </div>
                <div class="slide">
                    <div class="heading">
                        <img src="https://www.jessicagavin.com/wp-content/uploads/2020/12/how-to-make-risotto-22-1200.jpg">
                    </div>
                    <div class="desc">
                        <p>Italians</p>
                    </div>
                </div>
            </div>
        </div>
        <footer>
            
        </footer>
    </div>
</body>
</html>

home/templates/home/cart.html
{% extends 'base.html' %}

{% block content %}
<br><br><br>
<h1>Cart</h1>
<hr>
<a href="{% url 'home:list-menus' res_id %}" class="btn btn-primary shadow">Back to Menu</a>
<br> <br>
<div class="row g-4">
    {% for menu in menus %}
    
    <div class="col-sm-6 col-md-6 col-xs-4 col-lg-3">

        <div class="card shadow" style="width: 18rem;background-color: rgb(255, 240, 198);">
            <img src="{{menu.image}}" class="card-img-top" alt="No Image for this Food!"> 
            <div class="card-body">
              <h5 class="card-title">{{menu.food_name}}</h5>
              <p class="card-text">Rs. {{menu.price}}</p>
              <a href="{% url 'home:remove-cart' menu.id %}" class="btn btn-danger shadow">Remove</a>
            </div>
          </div>
    </div>
    {% empty %}
    <h5>Your cart is empty!</h5>
    {% endfor %}
</div>
<br><br>
<p class="lead">Total: Rs.{{cart.price}}</p>
<a href="{% url 'home:check-out' cart.id %}" class="btn btn-success shadow">Check Out (Cash On Delivery)</a>

{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}

{% block style %}
<style>
  .inner{
    overflow: hidden;
  }

  .inner img{
    transition: all 1.5s ease
  }

  .inner:hover img{
    transform: scale(1.5);
  }
</style>    
{% endblock %}

{% block content %}

<br><br>
<h1 class="text-warning">Welcome to HungerHive</h1>
{% if request.user.is_authenticated %}
<p>Hello {{user.username}}, please pick your favourite restaurant</p>
{% endif %}
<br>

<div class="row g-3">
    {% for restaurant in restaurants %}
    
    <div class="col-sm-8 col-md-5 col-xs-3 col-lg-3">
        <div class="card shadow" style="width: 18rem; background-color: rgb(255, 240, 198);">
          <div class="inner" style="overflow: hidden;">
            <img src="{{restaurant.image}}" class="card-img-top" alt="No Image">
          </div>  
            <div class="card-body">
              <h5 class="card-title">{{restaurant.name}}</h5>
              <p class="card-text">{{restaurant.description}}</p>
              <a href="{% url 'home:list-menus' restaurant.id %}" class="btn btn-warning shadow">Menu</a>
            </div>
          </div>
    </div>
    {% endfor %}
    
</div>
{% endblock %}

home/templates/home/index_res.html
{% extends 'base.html' %}

{% block style %}
<style>
  .inner{
    overflow: hidden;
  }

  .inner img{
    transition: all 1.5s ease
  }

  .inner:hover img{
    transform: scale(1.5);
  }
</style>    
{% endblock %}

{% block content %}

<br>

<h1>{{res.owner.username}}</h1>

{% if request.user.is_authenticated %}
<p>Happy business</p>
{% endif %}

<p>Owner: {{res.owner.username}}</p>
<p>Name: {{res.name}}</p>
<p class="lead">Limit: {{res.limit}} <span><a href="">Update Limit</a></span></p>
<hr>
<a href="{% url 'home:create-menu' %}">Add Menu</a>
<br> <br>
<h1>Your Menu</h1>
<div class="row g-3">
    {% for menu in menus %}
    
    <div class="col-sm-6 col-md-6 col-xs-4 col-lg-3" style="justify-content: center;">

        <div class="card shadow" style="width: 18rem; background-color: rgb(255, 240, 198);">
          <div class="inner" style="overflow: hidden;">
            <img src="{{menu.image}}" class="card-img-top" alt="No Image for this Food!">
          </div>  
            <div class="card-body">
              <h5 class="card-title">{{menu.food_name}}</h5>
              <p class="card-text">Price: {{menu.price}}</p>
            </div>
          </div>
    </div>
    {% endfor %}
    
</div>

{% endblock %}

home/templates/home/menu_create.html
{% extends 'base.html' %}

{% block content %}

<h1>Create New Menu</h1>

<form action="{% url 'home:create-menu' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Add Menu">
</form>

{% endblock %}

home/templates/home/menu_list.html
{% extends 'base.html' %}

{% block style %}
<style>
  .inner{
    overflow: hidden;
  }

  .inner img{
    transition: all 1.5s ease
  }

  .inner:hover img{
    transform: scale(1.5);
  }
</style>    

{% endblock %}

{% block content %}

<br>
<h1 class="text-warning">Menu of {{res.name}}</h1>
<p class="lead">Limit: {{res.limit}}</p>
<a href="{% url 'home:cart-view' res.id %}" class="btn btn-danger"><i class="fa fa-shopping-cart" style="font-size:24px"></i>  View Cart</a>
<br><br>
<div class="row g-4">
    {% for menu in menus %}
    
    <div class="col-sm-6 col-md-6 col-xs-4 col-lg-3">
        <div class="card shadow" style="width: 18re; background-color: rgb(255, 240, 198);">
            <div class="inner" style="overflow: hidden;">
              <img src="{{menu.image}}" class="card-img-top" alt="No Image for this Food!"> 
            </div>
            <div class="card-body">
              <h5 class="card-title" style="color: rgb(212, 122, 13)">{{menu.food_name}}</h5>
              <p class="card-text">Rs.{{menu.price}}</p>
              <a href="{% url 'home:add-cart' menu.id %}" style="align-self: center;" class="btn btn-warning shadow">Add to Cart</a>
              </div>
          </div>
    </div>
    {% endfor %}
    
</div>

{% endblock %}

home/templates/home/order_placed.html
{% extends 'base.html' %}

{% block content %}

<br><br>
<h1>Your Order is Placed Sucessfully!</h1>

<br>
<p class="lead">Total Price: Rs. {{price}}</p>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>{% endblock %}

home/templates/home/res_create.html
{% extends 'base.html' %}

{% block content %}

<h1 class="text-warning">Details of your Restaurant</h1>

<form action="{% url 'home:index' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Add">
</form>

{% endblock %}

home/templates/home/sambase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="base.css">
    <link rel="stylesheet" type="text/css" href="index.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div id="common">
        <div class="header">
            <nav>
                <ul>
                    <li><a>Home</a></li> 
                    <li><a>Contact</a></li> 
                    <li><a>Cart</a></li> 
                    <li><a>Sign up</a></li>
                </ul>
            </nav>
            <div class="catch">
                <div class="logo">
                    <img src="bee.png">
                </div>
                <h1>HungerHive</h1>
            </div>    
        </div>
        <div class="container">
            <h2><a>Categories</a></h2>
            <p>Let's start with your favourite kinds</p>
            <div class="row">
                <div class="slide">
                    <div class="heading">
                        <img src="https://www.jessicagavin.com/wp-content/uploads/2020/12/how-to-make-risotto-22-1200.jpg">
                    </div>
                    <div class="desc">
                        <p>Italians</p>
                    </div>
                </div>
                <div class="slide">
                    <div class="heading">
                        <img src="https://www.jessicagavin.com/wp-content/uploads/2020/12/how-to-make-risotto-22-1200.jpg">
                    </div>
                    <div class="desc">
                        <p>Italians</p>
                    </div>
                </div>
                <div class="slide">
                    <div class="heading">
                        <img src="https://www.jessicagavin.com/wp-content/uploads/2020/12/how-to-make-risotto-22-1200.jpg">
                    </div>
                    <div class="desc">
                        <p>Italians</p>
                    </div>
                </div>
                <div class="slide">
                    <div class="heading">
                        <img src="https://www.jessicagavin.com/wp-content/uploads/2020/12/how-to-make-risotto-22-1200.jpg">
                    </div>
                    <div class="desc">
                        <p>Italians</p>
                    </div>
                </div>
                <div class="slide">
                    <div class="heading">
                        <img src="https://www.jessicagavin.com/wp-content/uploads/2020/12/how-to-make-risotto-22-1200.jpg">
                    </div>
                    <div class="desc">
                        <p>Italians</p>
                    </div>
                </div>
                <div class="slide">
                    <div class="heading">
                        <img src="https://www.jessicagavin.com/wp-content/uploads/2020/12/how-to-make-risotto-22-1200.jpg">
                    </div>
                    <div class="desc">
                        <p>Italians</p>
                    </div>
                </div>
            </div>
        </div>
        <footer>
            
        </footer>
    </div>
</body>
</html>

templates/about.html
{% extends 'base.html' %}

{% block content %}

<h2 class="text-center mt-2">About Us</h2>
<hr>

<h4>Developed, Designed and Tested By:</h4>
<p>We are group of 3 friends pursuing undergraduate from Indian Institute of Information Technology , Design and Manufacturing , Chennai who are vastly interested in creating new ideas with interest.</p>
<ul>
    <li><a target="none" href="https://www.linkedin.com/in/divyamydv/">Divyam Yadav</a></li>
    <li><a target="none" href="https://www.linkedin.com/in/rohanshingre/">Rohan Shingre</a></li>
    <li><a target="none" href="https://www.linkedin.com/in/anonshubh/">Shubh Pathak</a></li>
</ul>
<p>Contact Us @ thesynergee@gmail.com</p>
<!-- <h2>Contributors: </h2> -->
<p>We encourage people to have a look at our repo on <a target="none" href="https://github.com/anonshubh/digi-connect">Github</a>, and provide us with feedback,suggestions and inputs. They are all very much apppreciated!!</p>


{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Custom CSS  -->
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Gloria+Hallelujah&family=Shalimar&family=Ubuntu:wght@300&display=swap');

      .container-fluid img{
        height: 50px; 
    }

    .card img {
      height: 270px;
      width: 100%;
      background-size: cover;
      background-position: center center;
    }
    .container-fluid{
      background: rgb(251, 224, 17);
      background: linear-gradient(0deg, rgba(255,239,116,1) 0%, rgba(255,255,255,1) 100%);
    }

    </style>
    {% block style %}
    {% endblock %}

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Fav-Icon  -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'image/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'image/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'image/fav/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'image/fav/site.webmanifest' %}">

    <!-- Google Font  -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lobster+Two:ital@1&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>{% block title %}HungerHive{% endblock %}</title>
    {% block head %} {% endblock %}
  </head>
  <body>
  
    <nav class="navbar navbar-expand-lg navbar-light sticky-top" style="padding: 0;">
      <div class="container-fluid">
        <div class="d-inline-flex">
          <img class="img" src="https://i.ibb.co/HTJWXSy/bee-removebg-preview.png">
          <a class="navbar-brand" style="color: rgb(206, 134, 0)!important; font-family: 'Gloria Hallelujah', sans-serif;" href="{% url 'home:index' %}"><h2>HungerHive</h2></a>  
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="">Your Orders</a>
            </li>
            <!-- <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                LookOut
              </a>
              <ul class="dropdown-menu nav-dropmenu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item a-white" href="">B</a></li>
                <li><a class="dropdown-item a-white" href="">C</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item a-white" href="">D</a></li>
              </ul>
            </li> -->
          </ul>
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
            </li>
            {% endif %}
          </ul>
        
        </div>
      </div>
    </nav>

    <!-- Main Content  -->
    <div class="container">
      {% include 'messages_.html' %}
      {% block content %} {% endblock %}
    </div>

    <br> <br><br><br>
      <!-- Grid container -->

      <!-- Copyright -->
      <div class="text-center p-3" style="background-color: rgba(253, 174, 2, 0.993);">
        © 2021 Copyright:
        <a class="text-white" href="https://hungerhive.herokuapp.com/">HungerHive</a>
      </div>
      <!-- Copyright -->
    </footer>
    <!-- Footer -->

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->

    <!-- Custom Js -->
    <script src="{% static 'js/master.js' %}"></script>

    <!-- Page-Wise JS -->
    {% block script %} {% endblock %}

  </body>
</html>

templates/messages_.html
{% for message in messages %}
  <div class="alert alert-blur mt-1 {{ message.tags }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% endfor %}

templates/policy.html
{% extends 'base.html' %}

{% block content %}
<h2 class="text-center mt-2">Terms & Policies</h2>
<a href="{% url 'connect:index' %}">Back To Home</a>
<hr>
<ol>
    <li>If found using Foul or Abusive Language you will be restricted for 5 days.</li>
    <li>If found harassing someone you will be permanently banned and judgement will be done under college rules for Anti Ragging.</li>
    <li>No Spamming Allowed. Spammers will be restricted for 3 days.</li>
    <li>Separate Division has been made in website for Freshers ( 1st year Btech) and other college students as per college's Anti Ragging Policy.</li>
    <li>Privacy Policy: Discloses the type of data you collect along with how it is stored and managed. This is a policy every arts organization should have.</li>
    <li>Terms of Service (TOS) Policy: Defines the rules by which an individual agrees to use a service. These are often called Terms of Use or Terms and Conditions. Although not always required by law, they are typically legally binding agreements that certainly help protect your organization and users.</li>
    <li>Disclaimer Policy: Indicates a site owner is not responsible for advice or information and limits liability. If your site includes content of a technical or legal nature, this is a must-have policy. Interestingly enough, this is one of the policies you’ll often find embedded into individual page alongside the respective content in addition to a general policy page or section.</li>
</ol>



{% endblock %}